apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
          # ES_MEM_LIMIT=2g
          # ES_JVM_HEAP=1024m
        ports:
        - name: rest
          containerPort: 9200
        - name: node
          containerPort: 9300  
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/elasticsearch/config
      volumes:
      - name: config-volume
        configMap:
          name: elasticsearch
