apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: monitoring
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: "redis"
      port: 6379
      targetPort: 6379
    - name: exporter
      port: 9121
      targetPort: 9121
  selector:
    app: redis
